### PR TITLE
Minutes and audio for 2020-12-01

### PR DESCRIPTION
**Pull request by rhiaro**
Minutes are cleaned. I don't know the last name of "Phil" who spoke during the meeting, so I have attributed using "Phil?" so scribetool doesn't mix up with Phil Archer. Will fix if someone else knows.

### CODE REVIEW

**Comment by vsnt** [comment]
Hey Amy, thanks for pr-actively doing this, but I have asked everyone doing these things for me, to include me. I actually want to know how these systems work, and everyone is changing things and updating things out from under me and not telling me/including me/enabling me to do it myself. Please invite me to look over your shoulder if you do this for my mtgs in the future. Thanks.

**Review by kimdhamilton — APPROVED** [review]

**Comment by kimdhamilton** [comment]
> I don't know the last name of "Phil" who spoke during the meeting, so I have attributed using "Phil?" so scribetool doesn't mix up with Phil Archer. Will fix if someone else knows.

That is Phil Long, alias "Phil-T3"

**Review by wyc — APPROVED** [review]
Thanks so much for your effort on this.

**Comment by kimdhamilton** [comment]
@rhiaro do you have permissions to merge? This should be good to go

**Comment by rhiaro** [comment]
@kimdhamilton sure, wasn't sure what the process is around who should merge it.. I'll wait 5 mins and if you haven't told me not to I will (or you can if you get there first..)

**Comment by kimdhamilton** [comment]
yes, go ahead and merge. As for the general process, we let the PR submitter merge. (Sometimes we'll merge it for people if it's a tiny change, but for bigger changes the submitter might be doing last minute tweaks)

**Pull request merged**
