### PR TITLE
Add minutes to 06-14 Meeting

### PR DESCRIPTION
**Pull request by kevinz917**

### CODE REVIEW

**Comment by msporny** [comment]
Apologies @kevinz917, I didn't know you were doing this as I had already committed the minutes last week: 

https://github.com/w3c-ccg/meetings/tree/gh-pages/2021-06-15-vchttpapi

Also, keep in mind that CI is failing for some email credentials reason... I'll talk w/ the Chairs about this.

@bumblefudge said that you were going to prep the minutes for the call today (thank you!). I'll make sure to NOT prep the minutes this time. 

I try to release the minutes the day of the call as I need to refer to them when processing issues, let me know your ETA on publishing when you get a chance.

In the meantime, closing this PR as it was applied last week.

**Comment by msporny** [comment]
My bad @kevinz917 -- I got totally confused... this PR is for the main call, not the VC HTTP API call... @bumblefudge didn't you say that @kevinz917 did the VC HTTP API call?

I think we need to merge this PR?

**Comment by bumblefudge** [comment]
whooooooops I think he scribed both calls but only uploaded minutes for the CCG main call, my mistake

**Comment by bumblefudge** [comment]
as for minutes today I'll PR the minutes in a few minutes.

**Comment by msporny** [comment]
> as for minutes today I'll PR the minutes in a few minutes.

Look at us... it used to be we couldn't find anyone to help w/ publishing transcriptions... and now... we're drowning in a deluge of transcriptors. Hooray for progress!

**Comment by bumblefudge** [comment]
sorry, how do i get the vc-http-api minutes from the scribe tool? querying by date it only gives me the CCG minutes...

**Comment by msporny** [comment]
<ccgbot> Raw transcript at https://meet.w3c-ccg.org/archives/w3c-ccg-vchttpapi-2021-06-22-irc.log
<ccgbot> Raw audio at https://meet.w3c-ccg.org/archives/w3c-ccg-vchttpapi-2021-06-22.ogg
<ccgbot> Raw video at https://meet.w3c-ccg.org/archives/w3c-ccg-vchttpapi-2021-06-22.mp4

**Comment by bumblefudge** [comment]
thanks that was in an old email, my bad.  will request privvies for the google doc and update for future volunteers 😄

**Pull request merged**
